export const SideLinks = [
  { name: "Model S" },
  { name: "Model 3" },
  { name: "Model X" },
  { name: "Model Y" },
  { name: "Solar Roof" },
  { name: "Solar Panels" },
  { name: "Existing Inventory" },
  { name: "Used Inventory" },
  { name: "Trade-In" },
  { name: "Test Drive" },
  { name: "Insurance" },
  { name: "Insurance" },
  { name: "Powerwall" },
  { name: "Powerwall" },
  { name: "Commercial Energy" },
  { name: "Utilities" },
  { name: "Charging" },
  { name: "Find Us" },
  { name: "Support" },
  { name: "Investor Relations" },
  { name: "Shop" },
  { name: "Account" },
  { name: "More" },
  { name: "United States", down: "English", last: true },
];
